Repository teamCleanie/ReFabBE, pull requests merged in 2024-11, with the labels that each got.

#8 S3 파일 업로드 기능 추가
  build.gradle
  src/main/java/cleanie/repatch/RepatchApplication.java
  src/main/java/cleanie/repatch/common/s3/config/AwsS3Properties.java
  src/main/java/cleanie/repatch/common/s3/config/S3Config.java
  src/main/java/cleanie/repatch/common/s3/helper/S3FileManager.java
  src/main/resources/application.yml
  src/test/java/cleanie/repatch/common/s3/helper/S3FileManagerTest.java
Labels: ✨ Feature

#10 CI/CD 파이프라인 구축
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  src/main/java/cleanie/repatch/RepatchApplication.java
  src/main/resources/logback-spring.xml
  src/main/resources/logback-test.xml
  src/test/java/cleanie/repatch/RepatchApplicationTests.java
  src/test/java/cleanie/repatch/setting/DummyTest.java
  src/test/java/cleanie/repatch/setting/annotation/AcceptanceTest.java
  src/test/java/cleanie/repatch/setting/annotation/IntegrationTest.java
  src/test/java/cleanie/repatch/setting/annotation/UnitTest.java
  src/test/java/cleanie/repatch/setting/model/TestType.java
  src/test/resources/application.yml
Labels: 🌏 Deploy, ⚙️ Setting

#12 API 문서 작성을 위한 spring rest docs 적용
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/cleanie/repatch/common/docs/config/SwaggerConfig.java
  src/main/java/cleanie/repatch/common/docs/example/HelloController.java
  src/test/java/cleanie/repatch/RepatchApplicationTests.java
  src/test/java/cleanie/repatch/common/docs/example/HelloControllerTest.java
  src/test/java/cleanie/repatch/setting/DummyTest.java
  src/test/resources/application.yml
Labels: ⚙️ Setting, 📝 Docs

#14 소셜 로그인 기능
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/cleanie/repatch/buyer/domain/Buyer.java
  src/main/java/cleanie/repatch/common/client/config/WebClientConfig.java
  src/main/java/cleanie/repatch/common/docs/config/SwaggerConfig.java
  src/main/java/cleanie/repatch/common/exception/EntityNotFoundException.java
  src/main/java/cleanie/repatch/common/exception/InvalidTokenException.java
  src/main/java/cleanie/repatch/common/exception/OAuthApiException.java
  src/main/java/cleanie/repatch/common/exception/UnAuthorizedAccessException.java
  src/main/java/cleanie/repatch/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/cleanie/repatch/common/exception/model/ExceptionCode.java
  src/main/java/cleanie/repatch/common/s3/config/AwsS3Properties.java
  src/main/java/cleanie/repatch/common/security/annotation/Auth.java
  src/main/java/cleanie/repatch/common/security/annotation/BuyerOnly.java
  src/main/java/cleanie/repatch/common/security/annotation/MemberOnly.java
  src/main/java/cleanie/repatch/common/security/annotation/SellerOnly.java
  src/main/java/cleanie/repatch/common/security/aspect/AuthorityChecker.java
  src/main/java/cleanie/repatch/common/security/component/AuthArgumentResolver.java
  src/main/java/cleanie/repatch/common/security/component/JwtTokenProvider.java
  src/main/java/cleanie/repatch/common/security/config/SecurityConfig.java
  src/main/java/cleanie/repatch/common/security/domain/Accessor.java
  src/main/java/cleanie/repatch/common/security/domain/Authority.java
  src/main/java/cleanie/repatch/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/cleanie/repatch/common/security/model/JwtProperties.java
  src/main/java/cleanie/repatch/common/web/config/WebConfig.java
  src/main/java/cleanie/repatch/seller/domain/Seller.java
  src/main/java/cleanie/repatch/user/client/KakaoApiClient.java
  src/main/java/cleanie/repatch/user/client/NaverApiClient.java
  src/main/java/cleanie/repatch/user/client/OAuthApiClient.java
  src/main/java/cleanie/repatch/user/component/UserReader.java
  src/main/java/cleanie/repatch/user/controller/AuthController.java
  src/main/java/cleanie/repatch/user/domain/User.java
  src/main/java/cleanie/repatch/user/domain/UserType.java
  src/main/java/cleanie/repatch/user/model/LoginStatus.java
  src/main/java/cleanie/repatch/user/model/OAuthProvider.java
  src/main/java/cleanie/repatch/user/model/OAuthUserInfo.java
  src/main/java/cleanie/repatch/user/model/request/OAuthLoginRequest.java
  src/main/java/cleanie/repatch/user/model/response/AuthResponse.java
  src/main/java/cleanie/repatch/user/model/response/KakaoUserResponse.java
  src/main/java/cleanie/repatch/user/model/response/NaverUserResponse.java
  src/main/java/cleanie/repatch/user/repository/UserRepository.java
  src/main/java/cleanie/repatch/user/service/AuthService.java
  src/main/java/cleanie/repatch/user/service/OAuthClientService.java
  src/main/resources/application.yml
  src/test/java/cleanie/repatch/common/docs/example/HelloControllerTest.java
  src/test/java/cleanie/repatch/setting/config/RestDocsConfiguration.java
  src/test/java/cleanie/repatch/setting/config/RestDocsTestSupport.java
  src/test/java/cleanie/repatch/user/controller/AuthControllerTest.java
  src/test/java/cleanie/repatch/user/domain/UserTest.java
Labels: ✨ Feature

#17 Spring REST Docs 동작 개선
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  docs/asciidoc/index.adoc
  src/main/java/cleanie/repatch/common/docs/config/SwaggerConfig.java
  src/main/java/cleanie/repatch/common/docs/example/HelloController.java
  src/main/java/cleanie/repatch/common/web/config/WebConfig.java
  src/main/java/cleanie/repatch/user/controller/AuthController.java
  src/main/resources/application.yml
  src/test/java/cleanie/repatch/user/controller/AuthControllerTest.java
Labels: 🐞 BugFix, 📝 Docs

#19 디스코드 웹훅 알람이 제대로 울리지 않는 문제 수정
  src/main/java/cleanie/repatch/common/exception/handler/GlobalExceptionHandler.java
  src/main/resources/logback-test.xml
Labels: 🐞 BugFix

#15 게시글 작성 기능
  build.gradle
  src/main/java/cleanie/repatch/RepatchApplication.java
  src/main/java/cleanie/repatch/common/domain/AuditorAwareImpl.java
  src/main/java/cleanie/repatch/common/domain/BaseEntity.java
  src/main/java/cleanie/repatch/common/exception/FileTypeMismatchException.java
  src/main/java/cleanie/repatch/common/exception/model/ExceptionCode.java
  src/main/java/cleanie/repatch/common/queryDsl/QueryDslConfig.java
  src/main/java/cleanie/repatch/common/s3/config/AwsS3Properties.java
  src/main/java/cleanie/repatch/common/s3/helper/S3FileManager.java
  src/main/java/cleanie/repatch/common/validation/annotation/ValidEnum.java
  src/main/java/cleanie/repatch/common/validation/annotation/ValidEnumSet.java
  src/main/java/cleanie/repatch/common/validation/validator/EnumIterableValidator.java
  src/main/java/cleanie/repatch/common/validation/validator/EnumValidator.java
  src/main/java/cleanie/repatch/draft/controller/DraftPostController.java
  src/main/java/cleanie/repatch/draft/domain/DraftPost.java
  src/main/java/cleanie/repatch/draft/domain/enums/DraftTransactionType.java
  src/main/java/cleanie/repatch/draft/domain/enums/DraftTransactionTypes.java
  src/main/java/cleanie/repatch/draft/model/request/DraftPostRequest.java
  src/main/java/cleanie/repatch/draft/model/response/DraftPostIdResponse.java
  src/main/java/cleanie/repatch/draft/model/response/DraftPostResponse.java
  src/main/java/cleanie/repatch/draft/repository/DraftPostRepository.java
  src/main/java/cleanie/repatch/draft/service/DraftPostService.java
  src/main/java/cleanie/repatch/photo/component/PhotosManager.java
  src/main/java/cleanie/repatch/photo/controller/PostPhotoController.java
  src/main/java/cleanie/repatch/photo/domain/DraftPhotos.java
  src/main/java/cleanie/repatch/photo/domain/PostPhoto.java
  src/main/java/cleanie/repatch/photo/domain/PostPhotos.java
  src/main/java/cleanie/repatch/photo/domain/enums/PhotoExtension.java
  src/main/java/cleanie/repatch/photo/model/request/PostPhotoUploadRequest.java
  src/main/java/cleanie/repatch/photo/model/response/PostPhotoResponse.java
  src/main/java/cleanie/repatch/photo/repository/PostPhotoRepository.java
  src/main/java/cleanie/repatch/photo/service/PostPhotoService.java
  src/main/java/cleanie/repatch/post/component/DraftPostManager.java
  src/main/java/cleanie/repatch/post/controller/PostController.java
  src/main/java/cleanie/repatch/post/domain/Post.java
  src/main/java/cleanie/repatch/post/domain/enums/FabricType.java
  src/main/java/cleanie/repatch/post/domain/enums/PostType.java
  src/main/java/cleanie/repatch/post/domain/enums/TransactionType.java
  src/main/java/cleanie/repatch/post/domain/enums/TransactionTypes.java
  src/main/java/cleanie/repatch/post/model/request/PostRequest.java
  src/main/java/cleanie/repatch/post/model/response/PostIdResponse.java
  src/main/java/cleanie/repatch/post/model/response/PostResponse.java
  src/main/java/cleanie/repatch/post/repository/PostRepository.java
  src/main/java/cleanie/repatch/post/service/PostService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#22 CloudFront 환경변수 추가
  .github/workflows/deploy.yml
  src/main/java/cleanie/repatch/RepatchApplication.java
  src/main/java/cleanie/repatch/common/domain/config/JpaAuditingConfig.java
  src/main/java/cleanie/repatch/common/s3/helper/S3FileManager.java
  src/test/java/cleanie/repatch/common/s3/helper/S3FileManagerTest.java
Labels: 🐞 BugFix
